spring:
  application:
    name: authentication

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  security:
    user:
      name: love
      password: love@123


server:
  port: 8086

frontend:
  url: ${FRONTEND_URL}

LIVTech:
  app:
    jwtSecret: your_jwt_secret_key_base64
    jwtExpirationMs: 86400000

    # 1 day in milliseconds

#email
  mail:
    host: smtp.gmail.com
    port: 587
    username: elijahmottey5@gmail.com
    password: jomzvxwckpbivnns
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
